# Generated by Django 2.0 on 2019-06-19 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userprofile_yunicon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='icon',
        ),
    ]
